Merged PR 2: Terraform script for EventHub
Since ability to manage eventhub namespace firewall and virtual network rules from Terraform is not supported yet (https://github.com/terraform-providers/terraform-provider-azurerm/issues/2579) we need to use ARM templates.

Another challenge - azurerm_template_deployment fails to pass "array" type parameters properly with error
Error: azurerm_template_deployment.eventhub: parameters (subnetIds): '' expected type 'string', got unconvertible type '[]interface {}’
(https://github.com/terraform-providers/terraform-provider-azurerm/issues/2579 closed but doesn’t seem resolved)

Related work items: #47